### ISSUE TITLE
Error occurred after upgrade to latest node

### ISSUE THREAD

**Issue by si3nloong** [jakobrosenberg/ppid-changed#1]
Node version : **v14.3.0**
NPM version : **6.14.5**

Some bug appear after upgraded to latest node version, i think node `fs` no longer support `writeFileSync` with number as input.

<img width="932" alt="Screenshot 2020-05-21 at 10 16 19 PM" src="https://user-images.githubusercontent.com/28108597/82568213-127e3880-9bb1-11ea-8174-080521f69780.png">

**Comment by jakobrosenberg** [comment]
Thanks @si3nloong . Interested in creating a PR?

**Comment by si3nloong** [comment]
kindly refer to PR #2

**Comment by jakobrosenberg** [comment]
PR merged and published. Thanks again!
